apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: <docker_registry>/my-image:latest
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: <mysql_host>
            - name: MYSQL_USER
              value: <mysql_user>
            - name: MYSQL_PASSWORD
              value: <mysql_password>
            - name: MYSQL_DATABASE
              value: <mysql_database>
